In [3]:
import pandas as pd
df = pd.read_csv("CRMLSListing_with_rates.csv")
print(df.shape)

/var/folders/d_/gll3jlg1445_2nm3xgq_xvdc0000gn/T/ipykernel_18427/669314064.py:2: DtypeWarning: Columns (0: ListAgentEmail, 1: BuyerAgencyCompensationType) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("CRMLSListing_with_rates.csv")

(566673, 87)

Step 1  Process Date Fields

In [4]:

date_cols = [
    "CloseDate",
    "PurchaseContractDate",
    "ListingContractDate",
    "ContractStatusChangeDate",
]
print(df[date_cols].dtypes)
print(df[date_cols].head(3))

CloseDate                   str
PurchaseContractDate        str
ListingContractDate         str
ContractStatusChangeDate    str
dtype: object
  CloseDate PurchaseContractDate ListingContractDate ContractStatusChangeDate
0       NaN           2024-05-07          2024-01-01               2024-05-07
1       NaN                  NaN          2024-01-24               2024-01-24
2       NaN                  NaN          2024-01-12               2024-01-12

In [5]:
# Convert the date column to datetime.
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")
print(df[date_cols].dtypes)
print(df[date_cols].head(5))

CloseDate                   datetime64[us]
PurchaseContractDate        datetime64[us]
ListingContractDate         datetime64[us]
ContractStatusChangeDate    datetime64[us]
dtype: object
  CloseDate PurchaseContractDate ListingContractDate ContractStatusChangeDate
0       NaT           2024-05-07          2024-01-01               2024-05-07
1       NaT                  NaT          2024-01-24               2024-01-24
2       NaT                  NaT          2024-01-12               2024-01-12
3       NaT                  NaT          2024-01-20               2024-01-20
4       NaT                  NaT          2024-01-12               2024-01-12

In [6]:
print("CloseDate missing:", df["CloseDate"].isnull().sum())
print("PurchaseContractDate missing:", df["PurchaseContractDate"].isnull().sum())

CloseDate missing: 398467
PurchaseContractDate missing: 291528

NaT values represent missing datetime information. 
These occur when certain events, such as closing or contract signing, have not yet taken place or are not recorded.

In [7]:
# create date consistency flags

# A. listing date is after close date
df["listing_after_close_flag"] = (
    df["ListingContractDate"].notna() &
    df["CloseDate"].notna() &
    (df["ListingContractDate"] > df["CloseDate"])
)

# B. purchase date is after close date
df["purchase_after_close_flag"] = (
    df["PurchaseContractDate"].notna() &
    df["CloseDate"].notna() &
    (df["PurchaseContractDate"] > df["CloseDate"])
)

# C. negative timeline:
# listing date is after purchase date
df["negative_timeline_flag"] = (
    df["ListingContractDate"].notna() &
    df["PurchaseContractDate"].notna() &
    (df["ListingContractDate"] > df["PurchaseContractDate"])
)

#  check flag counts
print("Flag counts:")
print("listing_after_close_flag:", df["listing_after_close_flag"].sum())
print("purchase_after_close_flag:", df["purchase_after_close_flag"].sum())
print("negative_timeline_flag:", df["negative_timeline_flag"].sum())
print()

Flag counts:
listing_after_close_flag: 74
purchase_after_close_flag: 266
negative_timeline_flag: 277

In [8]:
print("Rows with listing_after_close_flag = 1")
print(df.loc[df["listing_after_close_flag"] == 1,
             ["ListingContractDate", "PurchaseContractDate", "CloseDate"]].head())

print("\nRows with purchase_after_close_flag = 1")
print(df.loc[df["purchase_after_close_flag"] == 1,
             ["ListingContractDate", "PurchaseContractDate", "CloseDate"]].head())

print("\nRows with negative_timeline_flag = 1")
print(df.loc[df["negative_timeline_flag"] == 1,
             ["ListingContractDate", "PurchaseContractDate", "CloseDate"]].head())

Rows with listing_after_close_flag = 1
      ListingContractDate PurchaseContractDate  CloseDate
1406           2024-01-31           2024-01-15 2024-01-30
4140           2024-01-26           2024-01-10 2024-01-25
16407          2024-01-02           2023-12-04 2024-01-01
41873          2024-03-21           2024-03-03 2024-03-20
73360          2024-04-08           2024-03-27 2024-03-29

Rows with purchase_after_close_flag = 1
     ListingContractDate PurchaseContractDate  CloseDate
309           2024-01-31           2024-03-04 2024-01-31
919           2024-01-31           2024-02-05 2024-01-31
974           2024-01-29           2024-02-04 2024-01-29
1271          2024-01-29           2024-02-01 2024-01-29
4136          2024-01-25           2024-01-26 2024-01-25

Rows with negative_timeline_flag = 1
      ListingContractDate PurchaseContractDate  CloseDate
1406           2024-01-31           2024-01-15 2024-01-30
1712           2024-01-18           2024-01-05 2024-01-30
2665           2024-01-29           2024-01-08 2024-01-29
4140           2024-01-26           2024-01-10 2024-01-25
12206          2024-01-11           2024-01-09 2024-02-01

In [9]:
# High-Missing Columns (≥90%)
missing_pct = df.isnull().mean() * 100
high_missing_cols = missing_pct[missing_pct >= 90].index.tolist()
print("High-missing cols:", len(high_missing_cols))

# Non-analytical Column
extra_drop = [
    "ListAgentEmail",
    "ListAgentFirstName", "ListAgentLastName", "ListAgentFullName",
    "CoListAgentFirstName", "CoListAgentLastName",
    "BuyerAgentFirstName", "BuyerAgentLastName",
    "BuyerAgentMlsId", "BuyerAgencyCompensationType",
    "BuyerOfficeAOR",
]
extra_drop = [col for col in extra_drop if col in df.columns]
print("Manual drop cols:", len(extra_drop))

before_cols = df.shape[1]
# Execute Deletion
df = df.drop(columns=high_missing_cols)
df = df.drop(columns=extra_drop)

after_cols = df.shape[1]

print("===== Check Deletion =====")
print("Before:", before_cols)
print("After:", after_cols)
print("Removed:", before_cols - after_cols)

High-missing cols: 13
Manual drop cols: 11
===== Check Deletion =====
Before: 90
After: 66
Removed: 24

In [10]:
# ---------- Duplicate Column Check ----------
# 1. Suffix duplicates (.1, .2, etc.)
suffix_dups = [col for col in df.columns if col.endswith((".1", ".2", ".3"))]

# 2. Duplicate column names
name_dups = df.columns[df.columns.duplicated()].tolist()

# 3. Duplicate content columns
content_dups = []
cols = df.columns

for i in range(len(cols)):
    for j in range(i + 1, len(cols)):
        if df[cols[i]].equals(df[cols[j]]):
            content_dups.append((cols[i], cols[j]))

# ---------- Print Summary ----------
print("===== Duplicate Column Summary =====")
print(f"Suffix duplicates (.1 etc): {len(suffix_dups)}")
print(f"Duplicate column names: {len(name_dups)}")
print(f"Duplicate content pairs: {len(content_dups)}")
print("\n===== Duplicate Content Pairs =====")
for col1, col2 in content_dups:
    print(f"{col1}  <->  {col2}")

===== Duplicate Column Summary =====
Suffix duplicates (.1 etc): 11
Duplicate column names: 0
Duplicate content pairs: 9

===== Duplicate Content Pairs =====
ListingKey  <->  ListingKeyNumeric
Latitude  <->  Latitude.1
Longitude  <->  Longitude.1
UnparsedAddress  <->  UnparsedAddress.1
PropertyType  <->  PropertyType.1
LivingArea  <->  LivingArea.1
ListPrice  <->  ListPrice.1
DaysOnMarket  <->  DaysOnMarket.1
BuyerOfficeName  <->  BuyerOfficeName.1

In [11]:
print("Check equality:", df["ListingKey"].equals(df["ListingKeyNumeric"]))

print("Different rows:", (df["ListingKey"] != df["ListingKeyNumeric"]).sum())

print("\nSample data:")
print(df[["ListingKey", "ListingKeyNumeric"]].head(5))

Check equality: True
Different rows: 0

Sample data:
   ListingKey  ListingKeyNumeric
0  1074973329         1074973329
1  1074954552         1074954552
2  1074936537         1074936537
3  1074917818         1074917818
4  1074143166         1074143166

In [12]:
# ---------- Drop Duplicate Columns ----------

# 1. Drop suffix duplicates (.1, .2, etc.)
df = df.drop(columns=suffix_dups, errors="ignore")
print(f"Dropped {len(suffix_dups)} suffix duplicate columns")

# 2. Drop confirmed redundant column
df = df.drop(columns=["ListingKeyNumeric"], errors="ignore")
print("Dropped ListingKeyNumeric (duplicate of ListingKey)")

before_rows = df.shape[0]



# Remove duplicate rows 
# =========================
before = len(df)
df = df.drop_duplicates()
after = len(df)

print("\n[Listing]")
print(f"Before : {before:,} rows")
print(f"After  : {after:,} rows")
print(f"Removed: {before - after:,} duplicate rows")

Dropped 11 suffix duplicate columns
Dropped ListingKeyNumeric (duplicate of ListingKey)

[Listing]
Before : 566,673 rows
After  : 566,673 rows
Removed: 0 duplicate rows

In [13]:
#Check to ensure that the data type is correct
num_cols = [
    "ClosePrice",
    "ListPrice",
    "LivingArea",
    "DaysOnMarket",
    "BedroomsTotal",
    "BathroomsTotalInteger"
]

print(df[num_cols].dtypes)
for col in num_cols:
    print(f"\n--- {col} sample values ---")
    print(df[col].head(3))
for col in num_cols:
    print(f"{col} missing after conversion:", df[col].isna().sum())

ClosePrice               float64
ListPrice                float64
LivingArea               float64
DaysOnMarket               int64
BedroomsTotal            float64
BathroomsTotalInteger    float64
dtype: object

--- ClosePrice sample values ---
0   NaN
1   NaN
2   NaN
Name: ClosePrice, dtype: float64

--- ListPrice sample values ---
0    1340000.0
1    2500000.0
2    3150000.0
Name: ListPrice, dtype: float64

--- LivingArea sample values ---
0    1301.0
1    2788.0
2    3250.0
Name: LivingArea, dtype: float64

--- DaysOnMarket sample values ---
0    127
1      1
2      1
Name: DaysOnMarket, dtype: int64

--- BedroomsTotal sample values ---
0    2.0
1    4.0
2    6.0
Name: BedroomsTotal, dtype: float64

--- BathroomsTotalInteger sample values ---
0    2.0
1    3.0
2    4.0
Name: BathroomsTotalInteger, dtype: float64
ClosePrice missing after conversion: 419976
ListPrice missing after conversion: 0
LivingArea missing after conversion: 580
DaysOnMarket missing after conversion: 0
BedroomsTotal missing after conversion: 154
BathroomsTotalInteger missing after conversion: 57

In [14]:
# numeric columns
numeric_cols = [
    "ClosePrice",
    "OriginalListPrice",
    "ListPrice",
    "LivingArea",
    "LotSizeAcres",
    "DaysOnMarket",
    "YearBuilt",
    "BathroomsTotalInteger",
    "BedroomsTotal",
    "Latitude",
    "Longitude",
    "AssociationFee",
    "ParkingTotal",
    "GarageSpaces",
    "LotSizeSquareFeet",
    "rate_30yr_fixed"
]
# convert to numeric
for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")
# check data types
print("\nNumeric Column Types:")
print(df[numeric_cols].dtypes)

# preview
print("\nNumeric Columns Preview:")
print(df[numeric_cols].head(3))

Numeric Column Types:
ClosePrice               float64
OriginalListPrice        float64
ListPrice                float64
LivingArea               float64
LotSizeAcres             float64
DaysOnMarket               int64
YearBuilt                float64
BathroomsTotalInteger    float64
BedroomsTotal            float64
Latitude                 float64
Longitude                float64
AssociationFee           float64
ParkingTotal             float64
GarageSpaces             float64
LotSizeSquareFeet        float64
rate_30yr_fixed          float64
dtype: object

Numeric Columns Preview:
   ClosePrice  OriginalListPrice  ListPrice  LivingArea  LotSizeAcres  \
0         NaN          1340000.0  1340000.0      1301.0        4.0831
1         NaN          2500000.0  2500000.0      2788.0        0.1217
2         NaN          3150000.0  3150000.0      3250.0        0.2159

   DaysOnMarket  YearBuilt  BathroomsTotalInteger  BedroomsTotal   Latitude  \
0           127     1964.0                    2.0            2.0  34.052207
1             1     1994.0                    3.0            4.0  33.496363
2             1     1965.0                    4.0            6.0  34.119345

    Longitude  AssociationFee  ParkingTotal  GarageSpaces  LotSizeSquareFeet  \
0 -118.408445          2105.0           0.0           NaN           177861.0
1 -117.691677           254.0           3.0           3.0             5300.0
2 -118.111254             NaN           2.0           2.0             9404.0

   rate_30yr_fixed
0           6.6425
1           6.6425
2           6.6425

Step 3: Outlier Check (Invalid Values)

In [15]:
# Invalid value flags 
# -------------------------------

df["invalid_close_price_flag"] = (df["ClosePrice"] <= 0)
df["invalid_living_area_flag"] = (df["LivingArea"] <= 0)
df["invalid_days_on_market_flag"] = (df["DaysOnMarket"] < 0)
df["invalid_bedrooms_flag"] = (df["BedroomsTotal"] < 0)
df["invalid_bathrooms_flag"] = (df["BathroomsTotalInteger"] < 0)

# count
print("Invalid Value Counts:")
print(df[
    [
        "invalid_close_price_flag",
        "invalid_living_area_flag",
        "invalid_days_on_market_flag",
        "invalid_bedrooms_flag",
        "invalid_bathrooms_flag"
    ]
].sum())

Invalid Value Counts:
invalid_close_price_flag         0
invalid_living_area_flag       376
invalid_days_on_market_flag     29
invalid_bedrooms_flag            0
invalid_bathrooms_flag           0
dtype: int64

Step 4：Geographic Data Checks

In [16]:
# -------------------------------
# Geographic flags
# -------------------------------

# 1️ Missing Values
df["missing_geo_flag"] = (
    df["Latitude"].isna() | df["Longitude"].isna()
)

# 2️.Zero Values ​​(Dummy Data)
df["zero_geo_flag"] = (
    (df["Latitude"] == 0) | (df["Longitude"] == 0)
)

# 3.Incorrect longitude direction (California should be negative).
df["invalid_longitude_flag"] = (
    df["Longitude"] > 0
)

# 4️. Outside the California area (approximate range)
df["out_of_ca_flag"] = (
    (df["Latitude"] < 32) | (df["Latitude"] > 42) |
    (df["Longitude"] < -125) | (df["Longitude"] > -114)
)

# Count issues
print("Geographic Issues Count:")
print("missing_geo_flag:", df["missing_geo_flag"].sum())
print("zero_geo_flag:", df["zero_geo_flag"].sum())
print("invalid_longitude_flag:", df["invalid_longitude_flag"].sum())
print("out_of_ca_flag:", df["out_of_ca_flag"].sum())

Geographic Issues Count:
missing_geo_flag: 80441
zero_geo_flag: 65
invalid_longitude_flag: 86
out_of_ca_flag: 301

In [29]:
# -------------------------------
# Clean data: numeric + date + geo
# -------------------------------

before_rows = len(df)

df = df[
    # numeric validity
    (df["ClosePrice"] > 0) &
    (df["LivingArea"] > 0) &
    (df["DaysOnMarket"] >= 0) &
    (
        (df["BedroomsTotal"].isna()) |
        (df["BedroomsTotal"] >= 0)
    ) &
    (
        (df["BathroomsTotalInteger"].isna()) |
        (df["BathroomsTotalInteger"] >= 0)
    ) &

    # date validity
    (df["listing_after_close_flag"] == 0) &
    (df["purchase_after_close_flag"] == 0) &
    (df["negative_timeline_flag"] == 0) &

    # geo validity
    (df["zero_geo_flag"] == 0) &
    (df["invalid_longitude_flag"] == 0) &
    (df["out_of_ca_flag"] == 0)
].copy()

after_rows = len(df)

print("\nFinal Cleaning Summary:")
print("Rows before cleaning:", before_rows)
print("Rows after cleaning :", after_rows)
print("Rows removed        :", before_rows - after_rows)

Final Cleaning Summary:
Rows before cleaning: 146049
Rows after cleaning : 146049
Rows removed        : 0

In [ ]:
flag_cols = [
    "listing_after_close_flag",
    "purchase_after_close_flag",
    "negative_timeline_flag",
    "invalid_close_price_flag",
    "invalid_living_area_flag",
    "invalid_days_on_market_flag",
    "invalid_bedrooms_flag",
    "invalid_bathrooms_flag",
    "missing_geo_flag",
    "zero_geo_flag",
    "invalid_longitude_flag",
    "out_of_ca_flag"
]

df[flag_cols].sum().sort_values(ascending=False)

missing_geo_flag               15671
listing_after_close_flag           0
purchase_after_close_flag          0
negative_timeline_flag             0
invalid_close_price_flag           0
invalid_living_area_flag           0
invalid_days_on_market_flag        0
invalid_bedrooms_flag              0
invalid_bathrooms_flag             0
zero_geo_flag                      0
invalid_longitude_flag             0
out_of_ca_flag                     0
dtype: int64

week-6

In [36]:
import pandas as pd
import numpy as np

# Key Metrics to Create
# =============================

# 1. Price Ratio
df["price_ratio"] = np.where(
    df["OriginalListPrice"] > 0,
    df["ClosePrice"] / df["OriginalListPrice"],
    np.nan
)

# 2. Close-to-Original-List Ratio
df["close_to_original_list_ratio"] = np.where(
    df["OriginalListPrice"] > 0,
    df["ClosePrice"] / df["OriginalListPrice"],
    np.nan
)

# 3. Price Per Square Foot
df["price_per_sqft"] = np.where(
    df["LivingArea"] > 0,
    df["ClosePrice"] / df["LivingArea"],
    np.nan
)

# 4. Year / Month / YrMo
df["close_year"] = df["CloseDate"].dt.year
df["close_month"] = df["CloseDate"].dt.month
df["YrMo"] = df["CloseDate"].dt.to_period("M").astype(str)

# 5. Listing-to-Contract Days
df["listing_to_contract_days"] = (
    df["PurchaseContractDate"] - df["ListingContractDate"]
).dt.days

# 6. Contract-to-Close Days
df["contract_to_close_days"] = (
    df["CloseDate"] - df["PurchaseContractDate"]
).dt.days

# Sample output table
# =============================

sample_cols = [
    "CloseDate",
    "ClosePrice",
    "OriginalListPrice",
    "LivingArea",
    "price_ratio",
    "close_to_original_list_ratio",
    "price_per_sqft",
    "DaysOnMarket",
    "YrMo",
    "listing_to_contract_days",
    "contract_to_close_days"
]

print("\nSample engineered metrics:")
print(df[sample_cols].head(5))




# Save outputs
# =============================

#df.to_csv("CRMLSListing_Week6_Features.csv", index=False)
print("Saved: CRMLSListing_Week6_Features.csv")

Sample engineered metrics:
    CloseDate  ClosePrice  OriginalListPrice  LivingArea  price_ratio  \
9  2024-05-01   1262555.0          1249888.0      1899.0     1.010135
14 2024-03-15    650000.0           650000.0      1400.0     1.000000
18 2024-05-02    962500.0          1025000.0      1130.0     0.939024
20 2024-04-30    725000.0           725000.0      1250.0     1.000000
33 2024-04-09    730000.0           730000.0      1266.0     1.000000

    close_to_original_list_ratio  price_per_sqft  DaysOnMarket     YrMo  \
9                       1.010135      664.852554             0  2024-05
14                      1.000000      464.285714             0  2024-03
18                      0.939024      851.769912             0  2024-05
20                      1.000000      580.000000             0  2024-04
33                      1.000000      576.619273            35  2024-04

    listing_to_contract_days  contract_to_close_days
9                       20.0                    73.0
14                      10.0                    43.0
18                     104.0                     2.0
20                      18.0                    81.0
33                      35.0                    58.0
Saved: CRMLSListing_Week6_Features.csv

In [44]:
key_metrics = [
    'price_ratio',
    'price_per_sqft',
    'DaysOnMarket',
    'close_to_original_list_ratio',
    'listing_to_contract_days',
    'contract_to_close_days'
]

for m in key_metrics:
    print(f"{m}: {'exists' if m in df.columns else ' not found'}")

price_ratio: exists
price_per_sqft: exists
DaysOnMarket: exists
close_to_original_list_ratio: exists
listing_to_contract_days: exists
contract_to_close_days: exists

In [38]:
# Segment summary table
# 1.Grouped by CountyOrParish
# =============================

county_summary = (
    df.groupby("CountyOrParish")
    .agg(
        total_sales=("ClosePrice", "count"),
        median_close_price=("ClosePrice", "median"),
        average_close_price=("ClosePrice", "mean"),
        median_price_per_sqft=("price_per_sqft", "median"),
        average_days_on_market=("DaysOnMarket", "mean"),
        median_price_ratio=("price_ratio", "median"),
        average_listing_to_contract_days=("listing_to_contract_days", "mean"),
        average_contract_to_close_days=("contract_to_close_days", "mean")
    )
    .reset_index()
    .sort_values(by="median_close_price", ascending=False)
)

# Save outputs
# =============================
#county_summary.to_csv("Listing_county_segment_summary.csv", index=False)
print("Saved: Listing_county_segment_summary.csv")
pd.read_csv("Listing_county_segment_summary.csv")

Saved: Listing_county_segment_summary.csv

,CountyOrParish,total_sales,median_close_price,average_close_price,median_price_per_sqft,average_days_on_market,median_price_ratio,average_listing_to_contract_days,average_contract_to_close_days
0,San Mateo,3137,1758888.0,2.253103e+06,1094.470046,15.573797,1.032609,14.783870,19.490915
1,Santa Clara,7640,1644125.0,1.973980e+06,1002.880891,14.235471,1.042176,13.449215,20.748168
2,Marin,58,1298500.0,1.538981e+06,732.285750,21.931034,1.000000,22.982759,23.603448
3,San Francisco,396,1250000.0,1.402380e+06,938.883948,20.323232,1.029660,20.681818,20.202020
4,Santa Cruz,1146,1225000.0,1.358880e+06,756.674137,24.018325,1.000000,22.416230,21.675393
5,Alameda,8514,1187500.0,1.314600e+06,719.092525,17.940686,1.033333,18.167959,21.866690
6,Orange,16634,1175000.0,1.532075e+06,679.341890,20.770109,1.000000,27.219069,26.536492
7,Los Angeles,34921,915000.0,1.295495e+06,620.891161,23.804330,1.000000,27.933587,28.714810
8,Monterey,1443,910000.0,1.379744e+06,600.000000,23.128205,1.000000,22.962578,24.928621
9,San Diego,20127,900000.0,1.317319e+06,597.426471,20.004223,1.000000,24.399334,25.251515
10,Ventura,4524,857250.0,1.021601e+06,514.913972,30.557471,0.997104,34.839744,21.528957
11,San Luis Obispo,1916,848500.0,9.794687e+05,539.938647,22.837161,1.000000,29.530271,28.939457
12,Contra Costa,8165,843000.0,1.125069e+06,537.226277,19.365707,1.000555,19.932762,22.104593
13,Napa,47,818120.0,1.002463e+06,470.756063,33.829787,0.998331,34.255319,27.638298
14,San Benito,253,748000.0,8.188391e+05,415.789474,29.640316,1.000000,29.648221,26.711462
15,Sonoma,44,743000.0,8.212340e+05,434.481891,27.863636,1.000000,28.818182,19.409091
16,El Dorado,27,725000.0,7.431222e+05,378.985886,33.037037,1.000000,29.703704,25.555556
17,Santa Barbara,699,711000.0,1.363509e+06,434.379458,21.072961,1.000000,26.560801,28.512160
18,Placer,85,650000.0,6.923113e+05,320.851064,27.482353,0.989399,28.976471,22.647059
19,Mono,7,649000.0,7.128429e+05,667.695473,42.571429,1.000000,45.142857,18.000000
20,Mendocino,104,635000.0,8.185112e+05,415.486111,35.855769,0.967468,45.403846,29.413462
21,Inyo,4,635000.0,6.465000e+05,329.196418,38.500000,0.964956,39.250000,29.750000
22,San Joaquin,583,625000.0,6.627350e+05,315.712188,24.301887,1.000000,24.464837,27.782161
23,Riverside,17354,600000.0,7.230485e+05,325.978312,29.562637,0.994996,34.462146,26.998847
24,Solano,557,550000.0,5.713945e+05,342.931937,24.707361,1.000000,25.644524,23.752244
25,San Bernardino,11672,540826.5,6.357641e+05,342.171685,27.333533,1.000000,32.060401,31.981408
26,Yolo,28,533129.0,6.112021e+05,337.595161,21.464286,0.995327,23.857143,30.785714
27,Stanislaus,196,466000.0,4.883998e+05,278.429861,21.454082,0.993557,23.775510,26.535714
28,Sacramento,356,464500.0,4.949907e+05,309.064804,24.205056,1.000000,25.525281,24.196629
29,Calaveras,22,463962.5,5.436284e+05,283.062888,26.863636,0.974804,28.047619,23.666667
30,Colusa,11,459000.0,4.290364e+05,229.970326,14.818182,1.004135,18.181818,24.818182
31,Nevada,18,457750.0,6.338126e+05,318.474631,28.888889,0.975110,34.166667,24.777778
32,Yuba,40,431000.0,4.436975e+05,265.716667,31.750000,0.983232,39.575000,29.925000
33,Other State,3,424000.0,4.399000e+05,251.352977,25.333333,0.978893,26.000000,16.000000
34,Madera,342,415000.0,4.570166e+05,242.798084,31.213450,0.994056,35.470760,30.128655
35,Fresno,458,410000.0,4.804801e+05,259.291767,23.161572,1.000000,27.240175,28.971616
36,Merced,864,402495.0,4.243039e+05,258.046020,24.046296,1.000000,26.921296,27.121528
37,Butte,1337,402000.0,4.247378e+05,272.826681,25.335826,0.994241,29.673897,28.854151
38,Sutter,29,395000.0,3.838448e+05,263.824092,35.241379,1.000000,39.862069,27.793103
39,Tuolumne,14,394000.0,4.169643e+05,277.146778,56.214286,0.927444,49.642857,22.500000
40,Tulare,138,391370.0,4.153691e+05,232.343565,30.485507,1.000000,34.623188,28.992754
41,Mariposa,96,385000.0,4.291110e+05,243.265819,31.385417,0.982754,34.989583,34.947917
42,Amador,6,380000.0,3.529167e+05,233.796296,54.000000,0.925849,54.000000,30.666667
43,Clark,1,375000.0,3.750000e+05,285.605484,2.000000,0.974026,2.000000,9.000000
44,Kern,1175,372500.0,3.869560e+05,230.240550,28.031489,0.994286,31.617021,30.782128
45,Trinity,6,370000.0,4.027500e+05,204.542330,70.666667,0.964687,70.666667,49.666667
46,Shasta,26,356500.0,4.023865e+05,231.923823,41.538462,0.968904,47.384615,34.884615
47,Glenn,111,340000.0,3.572477e+05,245.670301,24.648649,1.000000,30.729730,30.972973
48,Modoc,1,339000.0,3.390000e+05,138.310894,93.000000,0.971347,93.000000,69.000000
49,Kings,88,338499.5,3.565514e+05,232.218597,21.397727,1.000000,23.750000,28.147727
50,Plumas,10,335000.0,3.311700e+05,273.264510,41.700000,0.972036,42.000000,34.000000
51,Tehama,95,325000.0,3.426145e+05,232.876712,32.505263,0.983294,40.231579,31.694737
52,Other County,1,325000.0,3.250000e+05,218.560861,24.000000,0.958702,24.000000,24.000000
53,Imperial,68,305500.0,3.095941e+05,207.522951,28.632353,1.000000,33.705882,22.647059
54,Lake,435,305000.0,3.170463e+05,211.769951,31.949425,0.974212,34.880460,29.110345
55,Siskiyou,13,260000.0,3.099154e+05,200.000000,51.384615,0.981964,53.692308,41.076923
56,Sierra,1,255000.0,2.550000e+05,222.902098,1.000000,0.944444,47.000000,38.000000
57,Lassen,3,200000.0,2.446667e+05,192.103996,13.666667,1.000000,14.333333,47.000000

In [ ]:
# =============================
# PropertyType + PropertySubType
# =============================

property_summary = (
    df.groupby(
        ["PropertyType", "PropertySubType"]
    )
    .agg(
        total_sales=("ClosePrice", "count"),
        median_close_price=("ClosePrice", "median"),
        average_close_price=("ClosePrice", "mean"),
        median_price_per_sqft=("price_per_sqft", "median"),
        average_days_on_market=("DaysOnMarket", "mean"),
        median_price_ratio=("price_ratio", "median")
    )
    .reset_index()
    .sort_values(
        by="median_close_price",
        ascending=False
    )
)

property_summary.to_csv(
   "Listing_property_segment_summary.csv",
    index=False
)
print("Saved: Listing_property_segment_summary.csv")
pd.read_csv("Listing_property_segment_summary.csv")

Saved: Listing_property_segment_summary.csv

,PropertyType,PropertySubType,total_sales,median_close_price,average_close_price,median_price_per_sqft,average_days_on_market,median_price_ratio
0,Residential,Farm,4,2031168.000,2.240584e+06,903.091337,52.750000,0.909713
1,Residential,Quadruplex,44,1287500.000,1.420486e+06,416.149134,34.636364,0.975417
2,Residential,Triplex,100,1065000.000,1.315369e+06,462.583197,29.180000,0.985638
3,Residential,SingleFamilyResidence,110084,930000.000,1.297215e+06,566.304034,22.055321,1.000000
4,Residential,Duplex,713,927500.000,1.253217e+06,568.942436,22.354839,1.000000
5,Residential,CoOwnership,4,844000.000,1.829500e+06,652.369138,19.250000,1.005562
6,Residential,Townhouse,8933,810000.000,9.965075e+05,567.466667,22.938542,1.000000
7,Residential,DeededParking,2,795000.000,7.950000e+05,500.190659,35.500000,0.988885
8,Residential,Timeshare,9,790000.000,6.624444e+05,312.871287,38.333333,1.000000
9,Residential,Loft,4,655444.445,6.037222e+05,494.627182,21.500000,1.000705
10,Residential,Condominium,23735,635000.000,8.753776e+05,574.792244,26.690036,0.996855
11,Residential,MixedUse,48,581000.000,7.980462e+05,400.163608,39.145833,0.991499
12,Residential,MobileHome,14,577000.000,6.480357e+05,675.900029,28.285714,0.961335
13,Residential,Studio,2,397495.000,3.974950e+05,804.698551,3.500000,0.970238
14,Residential,StockCooperative,442,376500.000,3.987422e+05,398.703743,24.038462,0.998998
15,Residential,ManufacturedHome,13,355000.000,3.356922e+05,196.428571,38.769231,0.993322
16,Residential,ManufacturedOnLand,1455,325000.000,6.374911e+05,227.272727,27.318900,0.985130
17,Residential,OwnYourOwn,18,270000.000,3.969087e+05,539.457922,15.277778,0.995337
18,Residential,Cabin,125,248000.000,2.696938e+05,277.777778,42.208000,0.936508
19,Residential,BoatSlip,24,182000.000,2.339708e+05,1725.000000,25.208333,0.969300

In [ ]:
# =============================
# CountyOrParish + MLSAreaMajor
# =============================

county_area_summary = (
    df.groupby(
        ["CountyOrParish", "MLSAreaMajor"]
    )
    .agg(
        total_sales=("ClosePrice", "count"),
        median_close_price=("ClosePrice", "median"),
        average_close_price=("ClosePrice", "mean"),
        median_price_per_sqft=("price_per_sqft", "median"),
        average_days_on_market=("DaysOnMarket", "mean"),
        median_price_ratio=("price_ratio", "median")
    )
    .reset_index()
    .sort_values(
        by="median_close_price",
        ascending=False
    )
)

county_area_summary.to_csv(
    "Listing_county_area_segment_summary.csv",
    index=False
)
print("Saved: Listing_county_area_segment_summary.csv")
pd.read_csv("Listing_county_area_segment_summary.csv")

Saved: Listing_county_area_segment_summary.csv

,CountyOrParish,MLSAreaMajor,total_sales,median_close_price,average_close_price,median_price_per_sqft,average_days_on_market,median_price_ratio
0,Los Angeles,C32 - Malibu Beach,21,11650000.0,1.427898e+07,2734.445042,48.952381,0.917431
1,Orange,SH - Shady Canyon,7,11000000.0,1.131711e+07,1455.604076,14.571429,1.000000
2,Orange,CR - Crystal Cove,10,10867500.0,1.569360e+07,2672.113498,18.700000,1.000000
3,Santa Barbara,MCTO - Montecito,38,7000000.0,7.638916e+06,1943.904471,30.578947,0.974302
4,Los Angeles,144 - Manhattan Bch Hill,10,6116500.0,6.653300e+06,1910.105021,15.500000,1.005263
...,...,...,...,...,...,...,...,...
1107,Kern,BFSH - Bodfish,3,105000.0,8.466667e+04,78.125000,17.666667,0.933333
1108,Kern,INYO - Inyokern,1,97000.0,9.700000e+04,67.361111,4.000000,1.000000
1109,San Bernardino,TRNA - Trona,7,75000.0,6.442857e+04,65.217391,27.142857,1.000000
1110,San Bernardino,BAKR - Baker,1,56000.0,5.600000e+04,41.666667,69.000000,0.949153
1111,Stanislaus,MP6 - Mariposa 6,1,40000.0,4.000000e+04,46.189376,58.000000,0.258065

In [42]:
# =============================
# ListOfficeName + BuyerOfficeName
# =============================

office_summary = (
    df.groupby(
        ["ListOfficeName", "BuyerOfficeName"]
    )
    .agg(
        total_sales=("ClosePrice", "count"),
        median_close_price=("ClosePrice", "median"),
        average_close_price=("ClosePrice", "mean"),
        median_price_per_sqft=("price_per_sqft", "median"),
        average_days_on_market=("DaysOnMarket", "mean"),
        median_price_ratio=("price_ratio", "median")
    )
    .reset_index()
    .sort_values(
        by="total_sales",
        ascending=False
    )
)

office_summary.to_csv(
    "Listing_office_segment_summary.csv",
    index=False
)
print("Saved: Listing_office_segment_summary.csv")
pd.read_csv("Listing_office_segment_summary.csv")

Saved: Listing_office_segment_summary.csv

,ListOfficeName,BuyerOfficeName,total_sales,median_close_price,average_close_price,median_price_per_sqft,average_days_on_market,median_price_ratio
0,Compass,Compass,3260,1599500.0,2.099091e+06,852.094925,16.531288,1.000000
1,Coldwell Banker Realty,Coldwell Banker Realty,1451,1295000.0,1.766256e+06,742.753623,17.178498,1.000000
2,Coldwell Banker Realty,Compass,637,1555000.0,1.933316e+06,850.000000,21.591837,1.000667
3,Compass,Coldwell Banker Realty,570,1650000.0,2.175208e+06,882.936137,20.228070,1.000000
4,Keller Williams Realty,Keller Williams Realty,536,930000.0,1.128303e+06,559.468233,17.162313,1.000000
...,...,...,...,...,...,...,...,...
84184,GE Realty,Coldwell Banker Realty,1,1390000.0,1.390000e+06,636.155606,28.000000,0.993567
84185,GE Realty,Aviara Real Estate,1,1200000.0,1.200000e+06,557.103064,45.000000,0.960001
84186,GE Dean and Associates,"eXp Realty of Greater Los Angeles, Inc.",1,1300000.0,1.300000e+06,606.909430,33.000000,1.000000
84187,GE Dean and Associates,"Zutila, Inc",1,920000.0,9.200000e+05,622.462788,8.000000,1.023359
84188,zRE Group,Team Laguna Inc,1,3025000.0,3.025000e+06,1996.699670,130.000000,0.945312